# Generated by Django 3.2.10 on 2022-12-14 19:14

from django.db import migrations, models
import prefixes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('nexthop', models.GenericIPAddressField()),
                ('metric', models.IntegerField(default=1000, validators=[prefixes.validators.metric_validator])),
            ],
        ),
        migrations.CreateModel(
            name='IPv6prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField()),
                ('nexthop', models.GenericIPAddressField()),
                ('metric', models.IntegerField(default=1000, validators=[prefixes.validators.metric_validator])),
            ],
        ),
        migrations.AddConstraint(
            model_name='ipv6prefix',
            constraint=models.UniqueConstraint(fields=('prefix', 'nexthop'), name='unique_v6_prefix_nexthop'),
        ),
        migrations.AddConstraint(
            model_name='ipv4prefix',
            constraint=models.UniqueConstraint(fields=('prefix', 'nexthop'), name='unique_v4_prefix_nexthop'),
        ),
    ]
